### ISSUE TITLE
No servers matched for domain

### ISSUE THREAD

**Issue by oslnx** [io-developer/php-whois#59] opened 2019-06-04 23:40 UTC
PHP Fatal error:  Uncaught Iodev\Whois\Exceptions\ServerMismatchException: No servers matched for domain 'domain.online'
PHP Fatal error:  Uncaught Iodev\Whois\Exceptions\ServerMismatchException: No servers matched for domain 'domain.gold'

this is a crap

**Comment by io-developer** [comment] 2019-06-05 12:59
'.online' works fine and was committed 18 April
'.gold' does not exists in https://github.com/io-developer/php-whois/blob/master/src/Iodev/Whois/Configs/module.tld.servers.json

It's possible to add custom TLD hosts (such as .gold and etc.) to initialized Whois instance. Please read "TLD hosts customization" section in README.md

P.S: please use bug/feature request template in next time

**Comment by jespinal** [comment] 2019-08-12 20:37
Hello:

First of all, it is an utter disrespect from that guy to call the package "a crap", if a package doesn't fit your needs, keep looking.

On the other hand, I also have problems with `.online` domains while using the latest version of the package (3.3.1)

This is the snippet of code used to test:

```
$whois = Iodev\Whois\Whois::create();

// This one fails too
//$result = $whois->LookupDomain("wrestle.online");
$result = $whois->LookupDomain("gamespot.online");
print_r($result);
die;
```

I downloaded the 3.3.1 package source in order to get sure that there's no difference between what `composer` had installed and your latest package:

`diff -Naur php-whois-3.3.1/ vendor/io-developer/php-whois/`

Absolutely no difference was shown.

Any pointers about where to look?

**Comment by io-developer** [comment] 2019-08-13 10:10
Hm, Still can't reproduce. I used your code:
```php
<?php

use Iodev\Whois\Helpers\ParserHelper;

require_once 'vendor/autoload.php';

$whois = \Iodev\Whois\Whois::create();

// This one fails too
//$result = $whois->LookupDomain("wrestle.online");
$result = $whois->LookupDomain("gamespot.online");
print_r($result);
die;
```

And get output
`php test.php `
```
Iodev\Whois\Modules\Tld\DomainResponse Object
(
    [domain:Iodev\Whois\Modules\Tld\DomainResponse:private] => gamespot.online
    [query:Iodev\Whois\Response:private] => gamespot.online

    [text:Iodev\Whois\Response:private] => Domain Name: gamespot.online                
Registry Domain ID: whois protect
Registrar WHOIS Server: whois.west.cn
Registrar URL: www.west.cn
Updated Date: 2015-08-31T11:23:29.0Z
Creation Date: 2015-08-31T11:23:29.0Z
Registrar Registration Expiration Date: 2021-08-31T11:23:29.0Z
Registrar: Chengdu west dimension digital technology Co., LTD
Registrar IANA ID: 1556
Reseller:
Domain Status: ok http://www.icann.org/epp#ok
Registry Registrant ID: xyz1853201313840
Registrant Name: REDACTED FOR PRIVACY
Registrant Organization: REDACTED FOR PRIVACY
Registrant Street: REDACTED FOR PRIVACY
Registrant City: Chengdu
Registrant State/Province: Sichuan
Registrant Postal Code: REDACTED FOR PRIVACY
Registrant Country: CN
Registrant Phone: REDACTED FOR PRIVACY
Registrant Phone Ext:
Registrant Fax: REDACTED FOR PRIVACY
Registrant Fax Ext:
Registrant Email: link at https://www.west.cn/web/whoisform?domain=gamespot.online
Registry Admin ID: xyz1853201313840
Admin Name: REDACTED FOR PRIVACY
Admin Organization: REDACTED FOR PRIVACY
Admin Street: REDACTED FOR PRIVACY
Admin City: Chengdu
Admin State/Province: Sichuan
Admin Postal Code: REDACTED FOR PRIVACY
Admin Country: CN
Admin Phone: REDACTED FOR PRIVACY
Admin Phone Ext:
Admin Fax: REDACTED FOR PRIVACY
Admin Fax Ext:
Admin Email: link at https://www.west.cn/web/whoisform?domain=gamespot.online
Registry Tech ID: xyz1853201313840
Tech Name: REDACTED FOR PRIVACY
Tech Organization: REDACTED FOR PRIVACY
Tech Street: REDACTED FOR PRIVACY
Tech City: Chengdu
Tech State/Province: Sichuan
Tech Postal Code: REDACTED FOR PRIVACY
Tech Country: CN
Tech Phone: REDACTED FOR PRIVACY
Tech Phone Ext:
Tech Fax: REDACTED FOR PRIVACY
Tech Fax Ext:
Tech Email: link at https://www.west.cn/web/whoisform?domain=gamespot.online
Name Server: ns1.sedoparking.com
Name Server: ns2.sedoparking.com
DNSSEC: signedDelegation
Registrar Abuse Contact Email: westabuse@gmail.com 
Registrar Abuse Contact Phone: +86.2862778877 ext 8359
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/ 
>>> Last update of WHOIS database: 2019-08-13T10:08:21.0Z <<<

For more information on Whois status codes, please visit https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en



    [host:Iodev\Whois\Response:private] => whois.west.cn
)
```

**Comment by io-developer** [comment] 2019-08-13 10:14
Try to fetch via cli whois (apt install whois)
```
whois gamespot.online --verbose
```

My output is:
```
Using server whois.nic.online.
Query string: "gamespot.online"

Domain Name: GAMESPOT.ONLINE
Registry Domain ID: D9889065-CNIC
Registrar WHOIS Server: whois.west.cn
Registrar URL: http://www.west.cn
Updated Date: 2018-01-30T13:18:07.0Z
Creation Date: 2015-08-31T11:23:22.0Z
Registry Expiry Date: 2021-08-31T23:59:59.0Z
Registrar: CHENGDU WEST DIMENSION DIGITAL TECHNOLOGY CO., LTD.
Registrar IANA ID: 1556
Domain Status: ok https://icann.org/epp#ok
Registrant Organization: xu yi
Registrant State/Province: bj
Registrant Country: CN
Registrant Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Admin Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Tech Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Name Server: NS1.SEDOPARKING.COM
Name Server: NS2.SEDOPARKING.COM
DNSSEC: unsigned
Billing Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Registrar Abuse Contact Email: abuse@west.cn
Registrar Abuse Contact Phone: +86.2862778877
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2019-08-13T10:12:23.0Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

>>> IMPORTANT INFORMATION ABOUT THE DEPLOYMENT OF RDAP: please visit
https://www.centralnic.com/support/rdap <<<

The Whois and RDAP services are provided by CentralNic, and contain
information pertaining to Internet domain names registered by our
our customers. By using this service you are agreeing (1) not to use any
information presented here for any purpose other than determining
ownership of domain names, (2) not to store or reproduce this data in
any way, (3) not to use any high-volume, automated, electronic processes
to obtain data from this service. Abuse of this service is monitored and
actions in contravention of these terms will result in being permanently
blacklisted. All data is (c) CentralNic Ltd (https://www.centralnic.com)

Access to the Whois and RDAP services is rate limited. For more
information, visit https://registrar-console.centralnic.com/pub/whois_guidance.
```


Also domain has custom WHOIS server (whois.west.cn). Maybe it's problem..

`whois gamespot.online -h whois.west.cn --verbose`
```
Using server whois.west.cn.
Query string: "gamespot.online"

Domain Name: gamespot.online                
Registry Domain ID: whois protect
Registrar WHOIS Server: whois.west.cn
Registrar URL: www.west.cn
Updated Date: 2015-08-31T11:23:29.0Z
Creation Date: 2015-08-31T11:23:29.0Z
Registrar Registration Expiration Date: 2021-08-31T11:23:29.0Z
Registrar: Chengdu west dimension digital technology Co., LTD
Registrar IANA ID: 1556
Reseller:
Domain Status: ok http://www.icann.org/epp#ok
Registry Registrant ID: xyz1853201313840
Registrant Name: REDACTED FOR PRIVACY
Registrant Organization: REDACTED FOR PRIVACY
Registrant Street: REDACTED FOR PRIVACY
Registrant City: Chengdu
Registrant State/Province: Sichuan
Registrant Postal Code: REDACTED FOR PRIVACY
Registrant Country: CN
Registrant Phone: REDACTED FOR PRIVACY
Registrant Phone Ext:
Registrant Fax: REDACTED FOR PRIVACY
Registrant Fax Ext:
Registrant Email: link at https://www.west.cn/web/whoisform?domain=gamespot.online
Registry Admin ID: xyz1853201313840
Admin Name: REDACTED FOR PRIVACY
Admin Organization: REDACTED FOR PRIVACY
Admin Street: REDACTED FOR PRIVACY
Admin City: Chengdu
Admin State/Province: Sichuan
Admin Postal Code: REDACTED FOR PRIVACY
Admin Country: CN
Admin Phone: REDACTED FOR PRIVACY
Admin Phone Ext:
Admin Fax: REDACTED FOR PRIVACY
Admin Fax Ext:
Admin Email: link at https://www.west.cn/web/whoisform?domain=gamespot.online
Registry Tech ID: xyz1853201313840
Tech Name: REDACTED FOR PRIVACY
Tech Organization: REDACTED FOR PRIVACY
Tech Street: REDACTED FOR PRIVACY
Tech City: Chengdu
Tech State/Province: Sichuan
Tech Postal Code: REDACTED FOR PRIVACY
Tech Country: CN
Tech Phone: REDACTED FOR PRIVACY
Tech Phone Ext:
Tech Fax: REDACTED FOR PRIVACY
Tech Fax Ext:
Tech Email: link at https://www.west.cn/web/whoisform?domain=gamespot.online
Name Server: ns1.sedoparking.com
Name Server: ns2.sedoparking.com
DNSSEC: signedDelegation
Registrar Abuse Contact Email: westabuse@gmail.com 
Registrar Abuse Contact Phone: +86.2862778877 ext 8359
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/ 
>>> Last update of WHOIS database: 2019-08-13T10:13:00.0Z <<<

For more information on Whois status codes, please visit https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en
```

**Comment by io-developer** [comment] 2019-08-13 10:32
Released latest master as v3.4.0

**Comment by jespinal** [comment] 2019-08-13 16:50
Hello, Sergey:

Thanks for the prompt reply to my comment.

I just tested the `3.4.0` release with the exact same code snippet you tested and **it is working as expected for both domains now**

In order to get sure I was not going nuts, I used the exact same snippet in different temporal directories where one had `3.3.1` version installed, and the other one `3.4.0` and I was able to verify that _something_ was not working as expected in `3.3.1`. The only difference between my snippet and the one I used, is that I included the following line in order to get sure I was indeed including the desired version:

`require 'vendor/autoload.php';'`

So far, it seems to be working smoothly. Thanks for your hard work and professionalism. I'll keep testing and report any issues (if any).

Best regards,

P. S. For the record, about your previous requests for CLI whois output, here you have (in case you want to debug locally):

`$ whois --verbose wrestle.online`

```
Using server whois.nic.online.
Query string: "wrestle.online"

Domain Name: WRESTLE.ONLINE
Registry Domain ID: D92502738-CNIC
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: https://namecheap.com
Updated Date: 2019-08-09T17:32:39.0Z
Creation Date: 2019-02-01T18:02:20.0Z
Registry Expiry Date: 2020-02-01T23:59:59.0Z
Registrar: Namecheap
Registrar IANA ID: 1068
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Registrant Organization: WhoisGuard, Inc.
Registrant State/Province: Panama
Registrant Country: PA
Registrant Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Admin Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Tech Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Name Server: NS1.HOSTPAPA.COM
Name Server: NS2.HOSTPAPA.COM
DNSSEC: unsigned
Billing Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Registrar Abuse Contact Email: abuse@namecheap.com
Registrar Abuse Contact Phone:
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2019-08-13T16:38:08.0Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

>>> IMPORTANT INFORMATION ABOUT THE DEPLOYMENT OF RDAP: please visit
https://www.centralnic.com/support/rdap <<<

The Whois and RDAP services are provided by CentralNic, and contain
information pertaining to Internet domain names registered by our
our customers. By using this service you are agreeing (1) not to use any
information presented here for any purpose other than determining
ownership of domain names, (2) not to store or reproduce this data in
any way, (3) not to use any high-volume, automated, electronic processes
to obtain data from this service. Abuse of this service is monitored and
actions in contravention of these terms will result in being permanently
blacklisted. All data is (c) CentralNic Ltd (https://www.centralnic.com)

Access to the Whois and RDAP services is rate limited. For more
information, visit https://registrar-console.centralnic.com/pub/whois_guidance.
```

`$ whois --verbose gamespot.online`

```
Using server whois.nic.online.
Query string: "gamespot.online"

Domain Name: GAMESPOT.ONLINE
Registry Domain ID: D9889065-CNIC
Registrar WHOIS Server: whois.west.cn
Registrar URL: http://www.west.cn
Updated Date: 2018-01-30T13:18:07.0Z
Creation Date: 2015-08-31T11:23:22.0Z
Registry Expiry Date: 2021-08-31T23:59:59.0Z
Registrar: CHENGDU WEST DIMENSION DIGITAL TECHNOLOGY CO., LTD.
Registrar IANA ID: 1556
Domain Status: ok https://icann.org/epp#ok
Registrant Organization: xu yi
Registrant State/Province: bj
Registrant Country: CN
Registrant Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Admin Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Tech Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Name Server: NS1.SEDOPARKING.COM
Name Server: NS2.SEDOPARKING.COM
DNSSEC: unsigned
Billing Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Registrar Abuse Contact Email: abuse@west.cn
Registrar Abuse Contact Phone: +86.2862778877
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2019-08-13T16:40:15.0Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

>>> IMPORTANT INFORMATION ABOUT THE DEPLOYMENT OF RDAP: please visit
https://www.centralnic.com/support/rdap <<<

The Whois and RDAP services are provided by CentralNic, and contain
information pertaining to Internet domain names registered by our
our customers. By using this service you are agreeing (1) not to use any
information presented here for any purpose other than determining
ownership of domain names, (2) not to store or reproduce this data in
any way, (3) not to use any high-volume, automated, electronic processes
to obtain data from this service. Abuse of this service is monitored and
actions in contravention of these terms will result in being permanently
blacklisted. All data is (c) CentralNic Ltd (https://www.centralnic.com)

Access to the Whois and RDAP services is rate limited. For more
information, visit https://registrar-console.centralnic.com/pub/whois_guidance.
```

**Additional info:**

`$ cat /etc/os-release `

```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

`$ whois --version`

```
Version 5.2.11.

Report bugs to <md+whois@linux.it>.
```

**Comment by io-developer** [comment] 2019-08-13 23:26
It's good!
Thanks for debug info. I guess this issue can be closed.

**Closed by io-developer** 2019-08-13 23:26 UTC
