### ISSUE TITLE
lookups fail for .fi domains 

### ISSUE THREAD

**Issue by nakuna** [io-developer/php-whois#13] opened 2018-03-19 15:18 UTC
.fi domains always return "Domain not found"

In io-developer/php-whois/src/Iodev/Whois/Whois.php:
```
private function loadDomainDataFrom(Server $server, $domain):
 $p = $server->getParser();
 $response = $this->loader->loadResponse($server->getHost(), $domain);
 $info = $p->parseResponse($response);
```
$info is always NULL.

In io-developer/php-whois/src/Iodev/Whois/Parsers/CommonParser.php:
```
public function parseResponse(Response $response)
 $group = $this->groupFrom($response);
```
$group is always NULL.

Something goes wrong in Iodev/Whois/Helpers/GroupHelper.php

**Comment by nakuna** [comment] 2018-03-20 10:41
Ficora whois has dots (".") after the field before ":" delimiter.  eg.

`domain.............: ficora.fi`

Fix:
io-developer/php-whois/src/Iodev/Whois/Helpers/GroupHelper.php:
```
-        preg_match_all('/^[ \t]*([^%#\r\n:]+):[ \t]*(.*?)\s*$/mui', $text, $m);
+        preg_match_all('/^[ \t]*([^%#\r\n:.]+)\.+:[ \t]*(.*?)\s*$/mui', $text, $m);

```

**Comment by io-developer** [comment] 2018-03-20 12:31
@nakuna, thanks for your feedback!
Currently I'm doing refactoring CommonParser and add new BlockParser which can cover your '.fi' case.
Issue confirmed and will be resolved in coming major version.

**Comment by nakuna** [comment] 2018-03-21 16:55
Ok, 
another related problem with Ficora, punycode and php-whois. Ficora whois doesn't have trailing dots in punycoded domain fields. As a result php-whois gets the "domain" key two times + some issues with unicode characters.

whois sisäministeriö.fi
```
[Querying whois.ficora.fi]
[whois.ficora.fi]
domain.............: sisäministeriö.fi
domain:   xn--sisministeri-icb5x.fi
```
Quick and dirty workaround; don't PCRE_UTF8, keep the dots, fix keys later, take only ASCII answers. This should work for punycoded and ASCII domains.

io-developer/php-whois/src/Iodev/Whois/Helpers/GroupHelper.php:
```
-        preg_match_all('/^[ \t]*([^%#\r\n:]+):[ \t]*(.*?)\s*$/mui', $text, $m);
-        foreach ($m[1] as $index => $key) {
-                $key = trim($key);
-                if ($key != 'http' && $key != 'https') {
-                        $group = array_merge_recursive($group, [$key => $m[2][$index]]);
-                }
-        }

+        preg_match_all('/^[ \t]*([^%#\r\n:]+):[ \t]*(.*?)\s*$/mi', $text, $m);
+        foreach ($m[1] as $index => $key) {
+                $key = trim($key);
+                $key=preg_replace('/\.*$/','',$key);
+            if ( $key != 'http' && $key != 'https' )
+                if ( $key!="domain" || idn_to_ascii($m[2][$index])==$m[2][$index] )
+                        $group = array_merge_recursive($group, [$key => $m[2][$index]]);
+        }
```

**Comment by io-developer** [comment] 2018-03-21 18:36
It's very helpful information. Thanks!

**Comment by io-developer** [comment] 2018-03-22 20:02
Good news!
Please check the latest commit in 'dev_add_parser' branch - https://github.com/io-developer/php-whois/commits/dev_add_parser
It passing two .fi tests
Is it done?

**Comment by io-developer** [comment] 2018-03-23 12:28
Now all latest changes in 'dev' - https://github.com/io-developer/php-whois/commits/dev

**Comment by nakuna** [comment] 2018-03-23 13:35
I had to change BlockParser.php to make it work.

dev_add_parser/src/Iodev/Whois/Parsers/BlockParser.php:
protected function groupFromText($text, $prevEmptyGroupText = '')
```
-        foreach (preg_split('~\r\n|[\r\n]~u', $text) as $line) {
+        foreach (preg_split('~\r\n|[\r\n]~', $text) as $line) {
```

**Comment by io-developer** [comment] 2018-03-23 13:57
Please describe what problem was resolved

**Comment by io-developer** [comment] 2018-03-23 18:10
I've got it.
Will be helpful if you can provide raw-text example where preg_split fails
Just copy-paste here

**Comment by nakuna** [comment] 2018-03-24 08:54
```
#$dom="sisäministeriö.fi";
$dom="xn--sisministeri-icb5x.fi";

# OK: outputs whois data 
$response = Whois::create()->lookupDomain($dom);
echo $response->getText();

# Not OK: $info NULL
$info = Whois::create()->loadDomainInfo($dom);
if (!$info) echo "Null if domain available";
else echo var_dump($info);

```
in Iodev/Whois/Parsers/BlockParser.php groupFromText function, the group is not splitted to lines.

With following change 
```
        foreach (preg_split('~\r\n|[\r\n]~u', $text) as $line) {
error_log("groupFromText preg_splits:$line");

```
Output is:
groupFromText preg_splits:
domain.............: sis�ministeri�.fi
domain:   xn--sisministeri-icb5x.fi
status.............: Registered
created............: 5.1.2018 10:46:30
expires............: 5.1.2023 10:46:30
available..........: 5.2.2023 10:46:30
RegistryLock.......: no

If I change 
```
-        foreach (preg_split('~\r\n|[\r\n]~u', $text) as $line) {
+        foreach (preg_split('~\r\n|[\r\n]~', $text) as $line) {

```

Output is:
groupFromText preg_splits:
groupFromText preg_splits:domain.............: sis�ministeri�.fi
groupFromText preg_splits:domain:   xn--sisministeri-icb5x.fi
groupFromText preg_splits:status.............: Registered
groupFromText preg_splits:created............: 5.1.2018 10:46:30
groupFromText preg_splits:expires............: 5.1.2023 10:46:30
groupFromText preg_splits:available..........: 5.2.2023 10:46:30
groupFromText preg_splits:RegistryLock.......: no

and $info is not NULL

**Comment by io-developer** [comment] 2018-03-24 13:28
Hm, looks like fread cant return unicode text.
Fixed in dev branch. Now it should work as well.
I tested by this code:
```php
<?php

use Iodev\Whois\Whois;

require_once 'vendor/autoload.php';

var_dump([
    'mb_internal_encoding BEFORE' => mb_internal_encoding(),
    'mb_regex_encoding BEFORE' => mb_regex_encoding(),
    'iconv_get_encoding(\'all\')' => iconv_get_encoding('all'),
]);

$info = Whois::create()->loadDomainInfo("sisäministeriö.fi");
var_dump($info);
```

**Comment by io-developer** [comment] 2018-03-24 13:31
![image](https://user-images.githubusercontent.com/6779324/37864485-ab7874f0-2f80-11e8-9929-f1b9e0075538.png)

All unicode symbols seems not broken

**Comment by nakuna** [comment] 2018-03-24 17:02
Nice! I can confirm that the latest dev branch works as expected.

**Comment by io-developer** [comment] 2018-03-24 17:54
Good =)

**Closed by io-developer** 2018-03-24 17:54 UTC
