### ISSUE TITLE
Notice: Array to string conversion 

### ISSUE THREAD

**Issue by smkbd** [io-developer/php-whois#127] opened 2020-07-09 19:24 UTC
**PHP-Whois version**: 4.0.0

**PHP version**: 7.4.4

**Description**  
I don't know exactly what is causing the notice-
`Notice: Array to string conversion in C:\xampp\htdocs\test\io-developer-whois\vendor\io-developer\php-whois\src\Iodev\Whois\Helpers\GroupHelper.php on line 142`
(This notice is produced 6 times in one run)

**How to reproduce**  
```
$whois = Factory::get()->createWhois();

if ($whois->isDomainAvailable("hostadvice.co")) {
    print "Bingo! Domain is available! :)";
}
else print "Nope";
```

**Possible Solution**  
I have no idea how to fix it. I am just suppressing the notice (until there is a fix by the devs) by adding an '@' sign before the isDomainAvailable method.
```
$whois = Factory::get()->createWhois();

if (@$whois->isDomainAvailable("hostadvice.co")) {
    print "Bingo! Domain is available! :)";
}
else print "Nope"; // No notice is visible this time
```

**Comment by bessone** [comment] 2020-11-09 13:48
Duplicate of #94

**Comment by zaherg** [comment] 2020-12-29 03:20
you might need to have a look at https://github.com/io-developer/php-whois/issues/94#issuecomment-751931853 

using the following code 
```php
        $whois = Factory::get()->createWhois();
        $info = $whois->loadDomainInfo($domain);
```

I got the following info (for sure there are more but my application returns only a few)

![image](https://user-images.githubusercontent.com/27624/103256287-b9278480-499d-11eb-8374-0b48af908921.png)

**Comment by io-developer** [comment] 2021-07-12 22:43
Can't reproduce. Possibly already fixed in master after parsing improvements.

**Closed by io-developer** 2021-07-12 22:43 UTC
